# Project Information
site_name: 'Cinematic Color 2'
site_url: 'http://cinematiccolor.org/'
site_description: 'Motion-Picture Color Management'
site_author: 'Cinematic Color 2 Authors'

# Repository
repo_name: 'colour-science/cinematiccolor'
repo_url: 'https://github.com/colour-science/cinematiccolor'

# Copyright
copyright: 'Copyright &copy; 2018 - <a href="mailto:ves-tech-color@googlegroups.com">Cinematic Color Authors</a>'

# Content
pages:
  - 'Motion-Picture Color Management': 'index.md'
  - 'Exploring Colorspaces': 'exploring-colorspaces.md'

# Theme
theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'white'
    accent: 'indigo'
  logo: 'assets/images/favicon.png'
  favicon: 'assets/images/favicon.ico'

# Style
# https://favicon.io/favicon-generator/?t=CC%C2%B2&ff=Roboto&fs=65&fc=%23FFFFFF&b=rounded&bc=%23000
extra_css:
  - 'assets/stylesheets/extra.css'

# Social
extra:
  social:
    - type: 'github'
      link: 'https://github.com/colour-science/cinematiccolor'
